
## Source Code Files

### configs/config.yaml
```yaml
# Configuration for i-HDC training
dataset:
  name: gtsrb  # Options: gtsrb, cifar10
  data_dir: ./data/GTSRB
  image_size: 64
  num_classes: 43  # 43 for GTSRB, 10 for CIFAR-10

model:
  name: i_hdc
  num_channels: 32  # Initial channels for MRF module
  dropout_rate: 0.5
  stochastic_depth_prob: 0.2

training:
  batch_size: 64
  epochs: 60
  optimizer: AdamW
  learning_rate: 0.001
  weight_decay: 0.001
  scheduler:
    type: ReduceLROnPlateau
    factor: 0.1
    patience: 5
  device: cuda  # Options: cuda, cpu

data_augmentation:
  gtsrb:
    rotation: 15
    color_jitter: 0.2
    perspective_distortion: 0.2
    random_grayscale: 0.1
  cifar10:
    horizontal_flip: 0.5
    random_crop: 4

checkpoint:
  save_dir: checkpoints
  save_freq: 10  # Save every 10 epochs
